local path = ...
local M = {}
M.mt = {}
M.names = nil

function M.get(colorscheme)
    if type(colorscheme) == 'table' then
        colorscheme = table.concat(colorscheme, "-")
    end
    local colors = require(path .. '.colors.' .. colorscheme)
    if M.names then
        for idx, fieldname in ipairs(M.names) do
            local basename = "base" .. string.format("%02X", idx)
            colors[fieldname] = colors[basename]
        end
    end
    return colors
end

function M.set_names(names)
    if type(names) == 'table' and #names == 16 then
        M.names = names
    end
end

function M.mt:__call(...)
    return M.get(...)
end

M.all = {
    "3024",
    "amarena",
    "apathy",
    "aquarium-dark",
    "ashes",
    "atelier-cave-light",
    "atelier-cave",
    "atelier-dune-light",
    "atelier-dune",
    "atelier-estuary-light",
    "atelier-estuary",
    "atelier-forest-light",
    "atelier-forest",
    "atelier-heath-light",
    "atelier-heath",
    "atelier-lakeside-light",
    "atelier-lakeside",
    "atelier-plateau-light",
    "atelier-plateau",
    "atelier-savanna-light",
    "atelier-savanna",
    "atelier-seaside-light",
    "atelier-seaside",
    "atelier-sulphurpool-light",
    "atelier-sulphurpool",
    "atlas",
    "bespin",
    "black-metal-bathory",
    "black-metal-burzum",
    "black-metal-dark-funeral",
    "black-metal-gorgoroth",
    "black-metal-immortal",
    "black-metal-khold",
    "black-metal",
    "black-metal-marduk",
    "black-metal-mayhem",
    "black-metal-nile",
    "black-metal-venom",
    "brewer",
    "bright",
    "brogrammer",
    "brushtrees-dark",
    "brushtrees",
    "chalk",
    "chocolate",
    "circus",
    "classic-dark",
    "classic-light",
    "codeschool",
    "cupcake",
    "cupertino",
    "darkmoss",
    "darktooth",
    "darkviolet",
    "decaf",
    "default-dark",
    "default-light",
    "dirtysea",
    "dracula",
    "edge-dark",
    "edge-light",
    "eighties",
    "embers",
    "equilibrium-dark",
    "equilibrium-gray-dark",
    "equilibrium-gray-light",
    "equilibrium-light",
    "espresso",
    "flat",
    "framer",
    "fruit-soda",
    "gigavolt",
    "github",
    "google-dark",
    "google-light",
    "grayscale-dark",
    "grayscale-light",
    "greenscreen",
    "gruvbox-dark-hard",
    "gruvbox-dark-medium",
    "gruvbox-dark-pale",
    "gruvbox-dark-soft",
    "gruvbox-light-hard",
    "gruvbox-light-medium",
    "gruvbox-light-soft",
    "hardcore",
    "harmonic-dark",
    "harmonic-light",
    "heetch-light",
    "heetch",
    "helios",
    "hopscotch",
    "horizon-dark",
    "horizon-light",
    "horizon-terminal-dark",
    "horizon-terminal-light",
    "humanoid-dark",
    "humanoid-light",
    "ia-dark",
    "ia-light",
    "icy",
    "irblack",
    "isotope",
    "macintosh",
    "marrakesh",
    "material-darker",
    "material-lighter",
    "material",
    "material-palenight",
    "materia",
    "material-vivid",
    "mellow-purple",
    "mexico-light",
    "mocha",
    "monokai",
    "mountain-fuji",
    "nord",
    "nova",
    "oceanicnext",
    "ocean",
    "onedark",
    "one-light",
    "outrun-dark",
    "papercolor-dark",
    "papercolor-light",
    "paraiso",
    "phd",
    "pico",
    "pop",
    "porple",
    "railscasts",
    "rebecca",
    "rose-pine-dawn",
    "rose-pine",
    "rose-pine-moon",
    "sandcastle",
    "seti",
    "shapeshifter",
    "snazzy",
    "solarflare",
    "solarized-dark",
    "solarized-light",
    "spacemacs",
    "summercamp",
    "summerfruit-dark",
    "summerfruit-light",
    "synth-midnight-dark",
    "tango",
    "tomorrow",
    "tomorrow-night-eighties",
    "tomorrow-night",
    "tube",
    "twilight",
    "unikitty-dark",
    "unikitty-light",
    "vulcan",
    "woodland",
    "xcode-dusk",
    "zenburn",
}

return setmetatable(M, M.mt)
